export const restaurants = [
  {
    id: 1,
    name: "Chinese Wok",
    rating: "3.2",
    deliveryTime: "35-40mins",
    cuisines: "Chinese , Asian , Tibetan",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e0839ff574213e6f35b3899ebf1fc597",
  },
  {
    id: 2,
    name: "Pizza Hut",
    rating: "4.3",
    deliveryTime: "25-30mins",
    cuisines: "Pizzas",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/7/17/ceed0515-9a2b-4eb3-84bd-0aebb73fbce8_89916.jpg",
  },
  {
    id: 3,
    name: "Burger King",
    rating: "3.4",
    deliveryTime: "20-25mins",
    cuisines: "Burgers",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/8/9/b7789646-9c37-46e2-a3b3-e8ec31a8c7c1_57276.jpg",
  },
  {
    id: 4,
    name: "Ghar Ka Tadka",
    rating: "4.2",
    deliveryTime: "30-35mins",
    cuisines: "Indian , Chinese",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/8/1/d693a687-a6ab-484d-bc79-0d6adb1a36f9_306919.jpg",
  },
];

export const mockRestaurants = [
  [
    {
      id: 1,
      name: "Chinese Wok",
      rating: "4.2",
      deliveryTime: "35-40mins",
      cuisines: "Chinese, Asian, Tibetan",
      imageUrl: "https://example.com/images/chinese-wok.jpg",
    },
    {
      id: 2,
      name: "Pasta Palace",
      rating: "4.5",
      deliveryTime: "30-35mins",
      cuisines: "Italian, Continental",
      imageUrl: "https://example.com/images/pasta-palace.jpg",
    },
    {
      id: 3,
      name: "Spice Hub",
      rating: "4.3",
      deliveryTime: "40-50mins",
      cuisines: "Indian, Mughlai",
      imageUrl: "https://example.com/images/spice-hub.jpg",
    },
    {
      id: 4,
      name: "Burger Shack",
      rating: "4.1",
      deliveryTime: "25-30mins",
      cuisines: "American, Fast Food",
      imageUrl: "https://example.com/images/burger-shack.jpg",
    },
    {
      id: 5,
      name: "Sushi Haven",
      rating: "4.8",
      deliveryTime: "50-60mins",
      cuisines: "Japanese, Seafood",
      imageUrl: "https://example.com/images/sushi-haven.jpg",
    },
    {
      id: 6,
      name: "Taco Town",
      rating: "4.0",
      deliveryTime: "20-25mins",
      cuisines: "Mexican, Tex-Mex",
      imageUrl: "https://example.com/images/taco-town.jpg",
    },
    {
      id: 7,
      name: "Green Bowl",
      rating: "4.6",
      deliveryTime: "30-40mins",
      cuisines: "Healthy, Vegan, Salads",
      imageUrl: "https://example.com/images/green-bowl.jpg",
    },
    {
      id: 8,
      name: "Steakhouse Supreme",
      rating: "4.7",
      deliveryTime: "45-55mins",
      cuisines: "Steak, Barbecue",
      imageUrl: "https://example.com/images/steakhouse-supreme.jpg",
    },
    {
      id: 9,
      name: "Cafe Delight",
      rating: "4.4",
      deliveryTime: "15-20mins",
      cuisines: "Cafe, Desserts, Coffee",
      imageUrl: "https://example.com/images/cafe-delight.jpg",
    },
    {
      id: 10,
      name: "Kebab Kingdom",
      rating: "4.5",
      deliveryTime: "35-45mins",
      cuisines: "Middle Eastern, Kebabs",
      imageUrl: "https://example.com/images/kebab-kingdom.jpg",
    },
    {
      id: 11,
      name: "Pizza Paradise",
      rating: "4.3",
      deliveryTime: "25-30mins",
      cuisines: "Pizza, Italian",
      imageUrl: "https://example.com/images/pizza-paradise.jpg",
    },
    {
      id: 12,
      name: "Ramen Express",
      rating: "4.6",
      deliveryTime: "40-50mins",
      cuisines: "Japanese, Ramen",
      imageUrl: "https://example.com/images/ramen-express.jpg",
    },
    {
      id: 13,
      name: "Crepe Corner",
      rating: "4.2",
      deliveryTime: "20-25mins",
      cuisines: "French, Desserts",
      imageUrl: "https://example.com/images/crepe-corner.jpg",
    },
    {
      id: 14,
      name: "The Greek Plate",
      rating: "4.3",
      deliveryTime: "30-35mins",
      cuisines: "Greek, Mediterranean",
      imageUrl: "https://example.com/images/the-greek-plate.jpg",
    },
    {
      id: 15,
      name: "BBQ Bliss",
      rating: "4.7",
      deliveryTime: "50-60mins",
      cuisines: "Barbecue, Grilled",
      imageUrl: "https://example.com/images/bbq-bliss.jpg",
    },
  ],
];
